#!/usr/bin/env bash
# Regenerate protobuf stubs from the shared proto definition.
# Run from the worker-bridge-e2b directory: bash scripts/gen_proto.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../" && pwd)"
PROTO_SRC="$REPO_ROOT/api/proto"
OUT_DIR="$SCRIPT_DIR/../src/worker_bridge_e2b/proto"

mkdir -p "$OUT_DIR"

uv run python -m grpc_tools.protoc \
    -I "$PROTO_SRC" \
    --python_out="$OUT_DIR" \
    --grpc_python_out="$OUT_DIR" \
    "registry/v1/registry.proto"

# fix relative import generated by grpc_tools
sed -i.bak 's/^from registry\.v1 import/from worker_bridge_e2b.proto.registry.v1 import/' \
    "$OUT_DIR/registry/v1/registry_pb2_grpc.py"
rm -f "$OUT_DIR/registry/v1/registry_pb2_grpc.py.bak"

# ensure __init__.py files exist
touch "$OUT_DIR/__init__.py"
touch "$OUT_DIR/registry/__init__.py"
touch "$OUT_DIR/registry/v1/__init__.py"

echo "Done: $OUT_DIR/registry/v1/"
